name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Set image tag using git commit hash
      # This gives every build a unique tag
      # Example: sankalpdesai/task-manager:a1b2c3d
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # What is GITHUB_SHA?
      # Every git commit has a unique ID called SHA
      # Example: a1b2c3d4e5f6...
      # We take first 7 characters as our image tag
      # This way every push creates a unique image version

      # Step 3 - Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4 - Build Docker image with unique tag
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ env.IMAGE_TAG }} .

      # Step 5 - Also tag as latest
      - name: Tag as latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/task-manager:latest

      # Step 6 - Push both tags to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:latest

      # Step 7 - Update deployment.yml with new image tag
      - name: Update Kubernetes deployment
        run: |
          sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/task-manager:.*|image: ${{ secrets.DOCKER_USERNAME }}/task-manager:${{ env.IMAGE_TAG }}|" k8s/deployment.yml

      # What is sed?
      # sed = stream editor, finds and replaces text in files
      # -i = edit file in place
      # s|old|new| = replace old with new
      # So we replace the image tag in deployment.yml
      # with the new commit hash tag

      # Step 8 - Commit updated deployment.yml back to GitHub
      - name: Commit updated deployment
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yml
          git commit -m "CI: update image tag to ${{ env.IMAGE_TAG }}"
          git push