# Name of our workflow
name: CI/CD Pipeline

# TRIGGER - when does this workflow run?
# Answer: every time code is pushed to main branch
on:
  push:
    branches:
      - main

# JOBS - what work needs to be done?
jobs:

  # Job 1 - Build and push Docker image
  build-and-push:

    # Which machine should run this job?
    # ubuntu-latest = GitHub gives us a free Linux machine
    runs-on: ubuntu-latest

    # STEPS - individual tasks inside this job
    steps:

      # Step 1 - Download our code onto the GitHub machine
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3 - Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/task-manager:latest .

      # Step 4 - Push image to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:latest